spring:
  application:
    name: mig-sasci
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mig-sasci
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2
          max-interval: 5000
        concurrency: 3
        max-concurrency: 5

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

swagger:
  version: 1.0
  description : APIs Cidadão